# Generated by Django 5.1.5 on 2025-06-14 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Logg', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signup',
            name='address',
        ),
        migrations.RemoveField(
            model_name='signup',
            name='confirm_password',
        ),
        migrations.RemoveField(
            model_name='signup',
            name='image',
        ),
        migrations.AddField(
            model_name='signup',
            name='address_line1',
            field=models.CharField(default='Not Provided', max_length=255),
        ),
        migrations.AddField(
            model_name='signup',
            name='city',
            field=models.CharField(default='Not Provided', max_length=50),
        ),
        migrations.AddField(
            model_name='signup',
            name='pincode',
            field=models.CharField(default='Not Provided', max_length=10),
        ),
        migrations.AddField(
            model_name='signup',
            name='profile_picture',
            field=models.ImageField(default='profile_pics/default.jpg', upload_to='profile_pics/'),
        ),
        migrations.AddField(
            model_name='signup',
            name='state',
            field=models.CharField(default='Not Provided', max_length=50),
        ),
        migrations.AddField(
            model_name='signup',
            name='user_type',
            field=models.CharField(choices=[('Patient', 'Patient'), ('Doctor', 'Doctor')], default='Patient', max_length=10),
        ),
    ]
