# Generated by Django 5.1.5 on 2025-06-14 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Logg', '0002_remove_signup_address_remove_signup_confirm_password_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=128)),
            ],
        ),
    ]
